{{- $name := include "basket.fullname" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "cfg-{{ $name }}"
  labels:
    app: {{ template "basket.name" . }}
    chart: {{ template "basket.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  CacheSettings: ConnectionString=basketdb:6379
  GrpcSettings_DiscountUrl: http://discount.grpc
  EventBusConnection: HostAddress=amqp://guest:guest@rabbitmq:5672
  ElasticConfiguration: Uri=http://elasticsearch:9200  