# This helm values file defines all infrastructure used by the app
# It is used on all charts, so ** MUST BE INCLUDED ** on every the app

inf:
  mesh:
    enabled: false          # True to enable Linkerd (set by deploy-all.ps1)
  tls:
    enabled: false          # True to enable TLS (set by deploy-all.ps1)
    issuer: ""              # cert-manager issuer to use for retrieving certs (set by deploy-all.ps1)
  k8s:                      # inf.k8s defines Kubernetes cluster global config
    dns:  "192.168.49.2"                # k8s external  DNS. This value or ip value MUST BE PROVIDED
    local: true            # True when deploying on "local K8s" provided by Docker Desktop.